//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenLoadDownloadRuPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenLoadDownloadRuPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;Authorization Denied!&lt;/title&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; media=&quot;screen&quot; href=&quot;main.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div id=&quot;container&quot;&gt;
        ///		&lt;header class=&quot;page-header&quot; role=&quot;banner&quot;&gt;
        ///			&lt;h1&gt;Authorization Denied!&lt;/h1&gt;
        ///		&lt;/header&gt;
        ///
        ///		&lt;main role=&quot;main&quot;&gt;
        ///			&lt;p class=&quot;h4&quot;&gt;
        ///				{0} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorResponseHtmlTemplate {
            get {
                return ResourceManager.GetString("ErrorResponseHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;В авторизации отказано!&lt;/title&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; media=&quot;screen&quot; href=&quot;main.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div id=&quot;container&quot;&gt;
        ///		&lt;header class=&quot;page-header&quot; role=&quot;banner&quot;&gt;
        ///			&lt;h1&gt;В авторизации отказано!&lt;/h1&gt;
        ///		&lt;/header&gt;
        ///
        ///		&lt;main role=&quot;main&quot;&gt;
        ///			&lt;p class=&quot;h4&quot;&gt;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorResponseHtmlTemplateRu {
            get {
                return ResourceManager.GetString("ErrorResponseHtmlTemplateRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning:#ffc1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainCss {
            get {
                return ResourceManager.GetString("MainCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pluso {
            get {
                object obj = ResourceManager.GetObject("pluso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;Successful Authorization!&lt;/title&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; media=&quot;screen&quot; href=&quot;main.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div id=&quot;container&quot;&gt;
        ///	&lt;header class=&quot;page-header&quot; role=&quot;banner&quot;&gt;
        ///		&lt;h1&gt;Successful Authorization!&lt;/h1&gt;
        ///	&lt;/header&gt;
        ///
        ///	&lt;main role=&quot;main&quot;&gt;
        ///		&lt;p class=&quot;h4&quot;&gt;
        ///			Yo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SuccessResponseHtml {
            get {
                return ResourceManager.GetString("SuccessResponseHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;Успешная авторизация!&lt;/title&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; media=&quot;screen&quot; href=&quot;main.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div id=&quot;container&quot;&gt;
        ///		&lt;header class=&quot;page-header&quot; role=&quot;banner&quot;&gt;
        ///			&lt;h1&gt;Успешная авторизация!&lt;/h1&gt;
        ///		&lt;/header&gt;
        ///
        ///		&lt;main role=&quot;main&quot;&gt;
        ///			&lt;p class=&quot;h4&quot;&gt;
        ///				Вы  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SuccessResponseHtmlRu {
            get {
                return ResourceManager.GetString("SuccessResponseHtmlRu", resourceCulture);
            }
        }
    }
}
